# - Samanvitha Matta (G01252738)
# - Akshaya Reddy Dundigalla (G01482843)
# - Tarun Naga Sai Chadaram (G01445928)
#The'studsurveextracred' container is deployed using Kubernetes to operate three replicas.
#A Docker Hub image is used, along with secret pulls and port 8080 exposure.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment645
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment645
  template:
    metadata:
      labels:
        app: deployment645
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: extracred-645
          image: tarunchadaram/studsurveextracred:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
