apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw3-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw3
  template:
    metadata:
      labels:
        app: hw3
    spec:
      containers:
      - name: hw3-container
        image: tarunchadaram/stusurvey-app:latest

        imagePullPolicy: Always
        ports:
        - containerPort: 8080
       
