apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment645
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment645
  template:
    metadata:
      labels:
        app: deployment645
    spec:
      containers:
        - name: extracred-645
          image: tarunchadaram/studsurvextracred:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
