apiVersion: v1
kind: Service
metadata:
  name: nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: deployment645
  ports:
    - port: 8080
      targetPort: 5001
      protocol: TCP
      nodePort: 32000
